#!/usr/bin/env python

import sys
import onebird
import predict_birds
import train_birds
import param_inf

onebird.doOneBird(sys.argv[2], sys.argv[3], Y=30, D=20, runs=3)
predict_birds.run(in_path=sys.argv[2], out_path=sys.argv[3], Y=3, D=20, steps=5)
train_birds.run(in_path=sys.argv[2], out_path=sys.argv[3], Y=3, D=20, steps=5)
param_inf.run(in_path=sys.argv[2], out_path=sys.argv[3], dataset=2,
              transitions=(100,100,25), iterations=50, runs=4 )

predict_birds.run(in_path=sys.argv[2], out_path=sys.argv[3], dataset=3, Y=3, D=20, steps=5)
train_birds.run(in_path=sys.argv[2], out_path=sys.argv[3], dataset=3, Y=3, D=20, steps=5)
param_inf.run(in_path=sys.argv[2], out_path=sys.argv[3], dataset=3,
              transitions=(100,100,25), iterations=50, runs=4 )


